### ISSUE TITLE
LoadError: StackOverflowError

### ISSUE THREAD

**Issue by andrewmaltezthomas** [nsgrantham/mimix#11]
Hi Neal, 

Thanks for making mimix available. I've tried running it using: 
`julia scripts/fit-mcmc.jl --hyper nutnet-analysis/configs/hyper.yml --monitor nutnet-analysis/configs/monitor-mimix.yml --inits nutnet-analysis/configs/inits.yml --factors 20 primm_mimix/reduced-data primm_mimix-results`

And got the following error:
`ERROR: LoadError: StackOverflowError:`
`Stacktrace:`
` [1] MvNormal(::Array{Float64,1}, ::Array{Float64,1}) at` `/Users/andrewthomas/.julia/packages/Mamba/Jotzr/src/distributions/constructors.jl:22 (repeats 79984 times)
in expression starting at /Users/andrewthomas/mimix/scripts/fit-mcmc.jl:105`

Any idea what this could be?

Thanks

**Comment by samd1993** [comment]
I had the same exact error if you look in the closed issues. He updated the script and then it worked for me. Did you just clone the mimix folder recently or was it awhile back? Might need to make sure everything is up to date.

**Comment by andrewmaltezthomas** [comment]
Hi Sam, 

Thanks for pointing this out. Updating Mamba worked.
