### ISSUE TITLE
Would you consider adding an explicit license?

### ISSUE THREAD

**Issue by stevenjkern** [nsgrantham/mimix#3]
I'm considering working on writing a Python implementation of a MIMIX model for a client project, and it would be of great benefit to see the Julia implementation in this repository, rather than working entirely off of the well-crafted paper. In the paper, you mention this repository as "open-source code", but without an explicit license, we have to regard the code here as unlicensed and are thus unable to view it in good conscience. Would you consider adding an explicit license to the repository? I would request a permissive license like an MIT or BSD, but of course the choices are entirely yours and your collaborators. Thank you so much!

**Comment by nsgrantham** [comment]
I thought I had added an MIT License long ago, but apparently not. Good luck on your Python implementation @stevenjkern, I'm happy to answer questions that may arise.
