### ISSUE TITLE
Dimension of monitored g

### ISSUE THREAD

**Issue by boyuren158** [nsgrantham/mimix#6]
It seems that the dimension of the monitored g parameter is not correct. The number of columns of g should be equal to the number of unique values of all blocking factors. But now it is equal to the number of blocking factors. The reason might be that in get_post function, line 72 of utils.jl, the second dim is not correctly specified.

**Comment by nsgrantham** [comment]
Ah, thanks for noticing. You are correct! I'll make the fix now.
