### ISSUE TITLE
Cannot "develop" the first script

### ISSUE THREAD

**Issue by samd1993** [nsgrantham/mimix#8]
Hi,

Thank you for posting everything on GitHub. I wanted to try out this script but cannot seems to run the first line of code you have in the ReadMe.

```
] develop MicrobiomeMixedModels.jl
] add StatsBase DataFrames Distributions Mamba YAML RCall CSV ArgParse
```

I get a syntax error:
`ERROR: syntax: extra token "MicrobiomeMixedModels" after end of expression`

Is this because of the newer version of Julia?
I downloaded the latest one but am aware you likely wrote this with an earlier version. 
Cheers,
Sam

**Comment by nsgrantham** [comment]
hmm, try removing the `.jl` after `MicrobiomeMixedModels`, does that fix the problem?

**Comment by samd1993** [comment]
Hi Neal,

I tried that with no avail. I get a similar error: 

```
julia> develop MicrobiomeMixedModels
ERROR: syntax: extra token "MicrobiomeMixedModels" after end of expression
Stacktrace:
 [1] top-level scope at REPL[1]:0
```

**Comment by samd1993** [comment]
And I've tried deleting the files and rerunning everything as well.

**Comment by nsgrantham** [comment]
Are you running the commands from within this repo?

I just tried the following with a fresh installation of Julia v1.4 and it worked for me.

```
git clone https://github.com/nsgrantham/mimix
cd mimix
```
Now we'll run julia (this is the path on my computer, if you're using a Mac it's probably the same)
```
/Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia
```
Then type `]` in the interpreter to enter Pkg mode (to install packages). Next type `develop MicrobiomeMixedModels.jl` and hit enter and it should install the code that lives in the `MicrobiomeMixedModels.jl` folder within the `mimix` repo.

Does that solve the problem?

**Comment by nsgrantham** [comment]
Rereading your code error, I think you may not be typing the `]`.

**Comment by samd1993** [comment]
I guess when you copy paste the bracket, you don't enter Pkg mode. After manually typing out the `]` it works fine. 
Looks like spending the last hour installing every version of Julia was a waste of time but hey glad it works now! :)
Thank you for the help

**Comment by nsgrantham** [comment]
Ah, I did not know that it wasn't copy-and-paste friendly. I'll add a note to the README so folks in the future don't encounter the same problem. Sorry about that, thanks for opening an issue and sticking with it.

**Comment by samd1993** [comment]
No problem. Quick sidenote: I was using GitBash on Windows to run this-- just in case this is a Windows specific error
